name: CI-Tests

on:
  push:
#    branches:
#    - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pre-install
      run: |
        sudo apt-get install libsuitesparse-dev
        sudo apt-get install autoconf automake libtool pkg-config python3-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel pytest pytest-cov
        pip install numpy==1.16.3
        pip install scipy==1.2.0
        pip install ephem>=3.7.6.0
        pip install Cython>=0.28.5
        pip install jplephem==2.6
        pip install setuptools>=40.0.0
        pip install scikit-sparse>=0.4.2 --no-binary scikit-sparse
        pip install astropy>=4.0,!=4.0.1,!=4.0.1.post1
        pip install healpy
    - name: Install other requirements
      run: |
        pip install git+https://github.com/nanograv/PINT.git@master
        pip install git+https://github.com/vallis/libstempo.git@master --install-option="--force-tempo2-install"
        pip install -r requirements_dev.txt
        python setup.py install
    - name: Display Python, pip, and setuptools version
      run: |
        python -c "import sys; print(f'Python {sys.version}')"
        python -c "import pip; print(f'pip {pip.__version__}')"
        python -c "import setuptools; print(f'setuptools {setuptools.__version__}')"
    - name: Run Tests
      run: pytest
